//! Rust code generation from the schema IR.
//!
//! Two hard rules, both load-bearing for `superquery build`:
//!
//! 1. **Generate from the IR, never from GraphQL.** If codegen needs something
//!    the IR does not carry, extend the IR. A second parser is how the
//!    platform ends up with two incompatible ideas of what a schema means.
//! 2. **Byte-for-byte determinism.** Same inputs must produce the same output,
//!    or the build hashes are worthless and reproducible builds are a lie.
//!    That means no `HashMap` iteration, no timestamps, no absolute paths in
//!    generated text.
//!
//! Milestone 4 of `docs/IMPLEMENTATION_PLAN.md`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod entities;
pub mod error;
pub mod metadata;
pub mod naming;
pub mod writer;

pub use error::{CodegenError, CodegenResult};
pub use writer::{OutputSet, write_output_set};

/// Header written at the top of every generated file.
///
/// Deliberately free of dates and paths: anything that varies between runs
/// would break the determinism the build format depends on.
pub const GENERATED_HEADER: &str =
    "// @generated by `superquery codegen`. Do not edit — your changes will be overwritten.\n";
