//! Reading contract ABIs and generating typed bindings.
//!
//! Decoding is not reimplemented here: the generated module hands the ABI to
//! [`alloy_sol_types::sol!`], which produces the decoder. This crate's job is
//! only to turn `abis/ERC20.json` into a deterministic `.rs` file.

use alloy_json_abi::JsonAbi;
use camino::Utf8Path;
use heck::ToSnakeCase;
use superquery_chain_api::{CodegenError, GeneratedFile, GeneratedModule};

/// A contract ABI loaded from disk, with the name it was declared under.
#[derive(Debug, Clone)]
pub struct LoadedAbi {
    /// The asset name from the manifest, e.g. `erc20`.
    pub name: String,
    /// The parsed ABI.
    pub abi: JsonAbi,
}

impl LoadedAbi {
    /// Read and parse an ABI JSON file.
    ///
    /// Accepts both a bare ABI array and an artifact object with an `abi` key,
    /// because both are what people actually have on disk.
    pub fn load(name: &str, path: &Utf8Path) -> Result<Self, CodegenError> {
        let source = std::fs::read_to_string(path).map_err(|source| CodegenError::Asset {
            path: path.to_string(),
            source,
        })?;

        let abi = parse_abi(&source).map_err(|e| {
            CodegenError::Invalid(format!("`{path}` is not a usable contract ABI: {e}"))
        })?;

        Ok(Self {
            name: name.to_owned(),
            abi,
        })
    }

    /// The module name generated code will use, e.g. `erc20`.
    pub fn module_name(&self) -> String {
        self.name.to_snake_case()
    }

    /// Generate the bindings module for this ABI.
    pub fn generate(&self) -> GeneratedModule {
        let module = self.module_name();
        GeneratedModule {
            name: module.clone(),
            files: vec![GeneratedFile {
                path: format!("contracts/{module}.rs"),
                contents: self.render(),
            }],
        }
    }

    /// Render the bindings source.
    ///
    /// Deterministic by construction: `JsonAbi` stores events in a `BTreeMap`,
    /// so iteration order does not depend on the input file's ordering.
    fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("// @generated by `superquery codegen`. Do not edit.\n");
        out.push_str(&format!("// Source ABI: {}\n\n", self.name));
        out.push_str("#![allow(clippy::all, missing_docs, non_snake_case)]\n\n");
        out.push_str("superquery_sdk::sol! {\n");

        for event in self.events() {
            out.push_str("    #[derive(Debug, serde::Serialize, serde::Deserialize)]\n");
            out.push_str(&format!("    {};\n", event.full_signature()));
        }

        out.push_str("}\n");
        out
    }

    /// Every event in the ABI, in deterministic order.
    pub fn events(&self) -> impl Iterator<Item = &alloy_json_abi::Event> {
        self.abi.events.values().flatten()
    }

    /// Every function in the ABI, in deterministic order.
    pub fn functions(&self) -> impl Iterator<Item = &alloy_json_abi::Function> {
        self.abi.functions.values().flatten()
    }
}

/// Parse an ABI from either a bare array or a build artifact object.
fn parse_abi(source: &str) -> Result<JsonAbi, String> {
    if let Ok(abi) = serde_json::from_str::<JsonAbi>(source) {
        return Ok(abi);
    }

    // Hardhat/Foundry artifacts wrap the ABI in an object.
    let value: serde_json::Value =
        serde_json::from_str(source).map_err(|e| format!("invalid JSON: {e}"))?;
    let inner = value
        .get("abi")
        .ok_or_else(|| "expected an ABI array, or an object with an `abi` key".to_owned())?;
    serde_json::from_value(inner.clone()).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    const ERC20_TRANSFER: &str = r#"[
      {
        "type": "event",
        "name": "Transfer",
        "inputs": [
          {"name": "from", "type": "address", "indexed": true},
          {"name": "to", "type": "address", "indexed": true},
          {"name": "value", "type": "uint256", "indexed": false}
        ],
        "anonymous": false
      }
    ]"#;

    #[test]
    fn parses_a_bare_abi_array() {
        let abi = parse_abi(ERC20_TRANSFER).unwrap();
        assert!(abi.events.contains_key("Transfer"));
    }

    #[test]
    fn parses_a_hardhat_style_artifact() {
        let artifact = format!(r#"{{"contractName":"ERC20","abi":{ERC20_TRANSFER}}}"#);
        let abi = parse_abi(&artifact).unwrap();
        assert!(abi.events.contains_key("Transfer"));
    }

    #[test]
    fn renders_a_sol_block_with_the_full_event_signature() {
        let loaded = LoadedAbi {
            name: "ERC20".to_owned(),
            abi: parse_abi(ERC20_TRANSFER).unwrap(),
        };
        let rendered = loaded.render();
        assert!(rendered.contains("superquery_sdk::sol! {"), "{rendered}");
        assert!(
            rendered.contains(
                "event Transfer(address indexed from, address indexed to, uint256 value);"
            ),
            "{rendered}"
        );
    }

    #[test]
    fn module_name_is_snake_case() {
        let loaded = LoadedAbi {
            name: "ERC20Vault".to_owned(),
            abi: parse_abi(ERC20_TRANSFER).unwrap(),
        };
        assert_eq!(loaded.module_name(), "erc20_vault");
        assert_eq!(loaded.generate().files[0].path, "contracts/erc20_vault.rs");
    }
}
